name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositories
        uses: actions/checkout@v2

      - name: Setup libs
        run: |
          sudo apt-get install -y libsfml-dev
          sudo apt-get install -y libgtest-dev

      - name: Check codestyle
        run: |
          git ls-files *.{c,h} | xargs clang-format -i --verbose
          git diff --exit-code

      - name: Build application
        run: make
        
      - name: Build ctests
        run: make ctest
